# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cross_entropy": "01_losses.ipynb",
         "weighted_cross_entropy": "01_losses.ipynb",
         "MALE": "01_losses.ipynb",
         "r2_score": "02_callbacks.ipynb",
         "prc_auc_score": "02_callbacks.ipynb",
         "Reg_EarlyStoppingAndPerformance": "02_callbacks.ipynb",
         "CLA_EarlyStoppingAndPerformance": "02_callbacks.ipynb",
         "count_trainable_params": "03_nets.ipynb",
         "resnet_block": "03_nets.ipynb",
         "Inception": "03_nets.ipynb",
         "MolMapNet": "03_nets.ipynb",
         "MolMapDualPathNet": "03_nets.ipynb",
         "MolMapAddPathNet": "03_nets.ipynb",
         "MolMapResNet": "03_nets.ipynb",
         "RegressionEstimator": "04_models.ipynb",
         "MultiClassEstimator": "04_models.ipynb",
         "MultiLabelEstimator": "04_models.ipynb"}

modules = ["losses.py",
           "callbacks.py",
           "nets.py",
           "models.py"]

doc_url = "https://riversdark.github.io/molmapnets/"

git_url = "https://github.com/riversdark/molmapnets/tree/master/"

def custom_doc_links(name): return None
