# AUTOGENERATED! DO NOT EDIT! File to edit: 03_esol.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
from torch import nn, optim
import torch.nn.functional as F
torch.set_default_dtype(torch.float64)

from torch.utils.data import Dataset, DataLoader, random_split