# AUTOGENERATED! DO NOT EDIT! File to edit: 01_losses.ipynb (unless otherwise specified).

__all__ = ['cross_entropy', 'weighted_cross_entropy', 'MALE']

# Cell
import tensorflow as tf
from sklearn.metrics import roc_auc_score
import numpy as np

# Cell
def cross_entropy(y_true, y_pred, MASK = -1):
    mask = tf.cast(tf.not_equal(y_true, MASK), tf.keras.backend.floatx())
    labels = y_true * mask
    logits = y_pred * mask
    cost = tf.nn.sigmoid_cross_entropy_with_logits(labels=labels, logits=logits)
    return cost

# Cell
def weighted_cross_entropy(y_true, y_pred, pos_weight, MASK = -1):

    mask = tf.cast(tf.not_equal(y_true, MASK), tf.keras.backend.floatx())
    labels = y_true * mask
    logits = y_pred * mask
    cost = tf.nn.weighted_cross_entropy_with_logits(labels=labels, logits=logits,
                                                    pos_weight = pos_weight)
    return cost

# Cell
def MALE(y_obs, y_pred):
    return tf.keras.backend.log(0.5 + tf.keras.backend.abs(y_pred - y_obs))